### ISSUE TITLE
Do not assume readmes are markdown

### ISSUE THREAD

**Issue by nagisa** [ligthyear/clippy-service#11]
Markup provided in “Just add this to your readme:” section will only work on markdown readmes, but not restructuredtext or plaintext ones.

At the very least a footnote about readme having to be markdown should be added?

**Comment by nagisa** [comment]
Ah I see a hidden option to change the format. Either way the “Just add this to your readme” should read as “Just add this to your [selected format] readme”.

**Comment by gnunicorn** [comment]
Yeah, using markdown is a tricky default. I personally also prefer other
formats, which is why this has more rendering formats than many other
badges. Unfortunately, I am not sure how to present those options nicely
without messing with the ease-of-use for first time users.

Hmm, maybe changing the text and allow to somehow change them on click
(make this visually clear in some way) or something would be nice.

I'll sleep over it, but gotta get back to the design of the page anyhows,
so I'll come up with something...
