### ISSUE TITLE
rustup + update clippy?

### ISSUE THREAD

**Issue by llogiq** [ligthyear/clippy-service#36]
It appears both your test and your clippy run fail recently (our badge shows a lot of errors) – do you use
- the latest clippy
- the latest nightly?

**Comment by gnunicorn** [comment]
It appears that our automatic rebuilding via travis is breaking because the docker build runs [out of memory on the deploy server](https://travis-ci.org/ligthyear/clippy-service/builds/122798884#L1645) regularly... thinking of using docker automatic builds to build the image and have a different dockerfile doing the actual deploy on dokku via a post-build-hook... dunno yet.

**Comment by gnunicorn** [comment]
I deployed a new process which builds the docker image on travis and pushes that to production directly rather than building it again there. This should fix this.
