### ISSUE TITLE
does not seem to be working

### ISSUE THREAD

**Issue by Eh2406** [ligthyear/clippy-service#41]
when I go to the page https://clippy.bashy.io/ the example badge dose not lode.

and when I enter a repo I do not get results.

[![Clippy Linting Result](https://clippy.bashy.io/github/mrhooray/kdtree-rs/master/badge.svg)](https://clippy.bashy.io/github/mrhooray/kdtree-rs/master/log)

**Comment by gnunicorn** [comment]
This appears to have been caused by the server running out of disk space – 40gig – somehow. I cleaned it up a little bit and it seems to be working fine for now, but I'll investigate how to prevent this in the future.

Please reopen if this is still broken for you or you have trouble with any specific repo.
