### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by Manishearth** [ligthyear/clippy-service#7]
I'm only going through the actual code; I'm not conversant with Docker and Vagrant and all those other newfangled tools :smile: 

I only really have minor comments; the code and design look good!

``` patch
diff --git a/src/clippy.rs b/src/clippy.rs
index ec716d9..53fb034 100644
--- a/src/clippy.rs
+++ b/src/clippy.rs
@@ -10,6 +10,7 @@ use std::path::Path;
 use std::vec::Vec;
 use std::{env, fs};

+// the enum should just have fields, e.g. Success, WithWarnings(u32), WithErrors(u32,u32)
 pub enum ClippyState {
     Success,
     WithWarnings,
diff --git a/src/handlers.rs b/src/handlers.rs
index 5425144..606c34b 100644
--- a/src/handlers.rs
+++ b/src/handlers.rs
@@ -47,6 +47,7 @@ pub fn github_finder(req: &mut Request) -> IronResult<Response> {
     match redis.get(redis_key.to_owned()) {
         // we have a cached value, redirect directly
         Ok(Value::Data(sha)) => {
+            // what if the sha changes? or is this handled by schedule_update?
             local_redir(&format!("/github/sha/{0}/{1}/{2}/{3}",
                                  user,
                                  repo,
@@ -93,11 +94,13 @@ pub fn github_finder(req: &mut Request) -> IronResult<Response> {
 pub fn github_handler(req: &mut Request) -> IronResult<Response> {

     let router = req.extensions.get::<Router>().unwrap();
+    // perhaps the redis connection should be set up once in main.rs?
     let redis: redis::Connection = setup_redis();

     let user = router.find("user").unwrap();
     let repo = router.find("repo").unwrap();
     let sha = router.find("sha").unwrap();
+    // this allocation is really unnecessary, you can just use an array of length 2 and fill it with the iterator. Or, just match on the full string.
     let filename: Vec<&str> = router.find("method")
                                     .unwrap_or("badge.svg")
                                     .rsplitn(2, '.')
diff --git a/src/helpers.rs b/src/helpers.rs
index ea23dcc..e920a30 100644
--- a/src/helpers.rs
+++ b/src/helpers.rs
@@ -63,6 +63,7 @@ pub fn download_and_unzip(source_url: &str, tmp_dir: &TempDir) -> Result<Vec<Str
                                     let mut buffer: Vec<u8> = vec![];
                                     zip_file.read_to_end(&mut buffer).unwrap();
                                     writer.write(&buffer).unwrap();
+                                    // why not just return a vec of paths?
                                     paths.push(String::from(full_path.to_string_lossy()
                                                                      .into_owned()));
                                 }
```

**Comment by gnunicorn** [comment]
Thanks, @Manishearth for the review, highly appreciated. I did the change with the Enum, great suggestion!

For the other things, please see the answers below:

``` diff
diff --git a/src/handlers.rs b/src/handlers.rs
index 5425144..606c34b 100644
--- a/src/handlers.rs
+++ b/src/handlers.rs
@@ -47,6 +47,7 @@ pub fn github_finder(req: &mut Request) -> IronResult<Response> {
     match redis.get(redis_key.to_owned()) {
         // we have a cached value, redirect directly
         Ok(Value::Data(sha)) => {
+            // what if the sha changes? or is this handled by schedule_update?
             local_redir(&format!("/github/sha/{0}/{1}/{2}/{3}",
                                  user,
                                  repo,
```

A Git SHA never changes – git commits are immutable. I think you might refer to the fact that branches (and tags) might reference a different SHA at another point in time. We solve this by only caching the redis-key for 5min (automagically done in `L75                        set_redis_cache(&redis, &redis_key, &sha);`) max. If asked after that time we resolve the branch-to-sha again (as redis doesn't return any valid result).

---

``` diff
diff --git a/src/handlers.rs b/src/handlers.rs
index 5425144..606c34b 100644
--- a/src/handlers.rs
+++ b/src/handlers.rs
@@ -93,11 +94,13 @@ pub fn github_finder(req: &mut Request) -> IronResult<Response> {
 pub fn github_handler(req: &mut Request) -> IronResult<Response> {

     let router = req.extensions.get::<Router>().unwrap();
+    // perhaps the redis connection should be set up once in main.rs?
     let redis: redis::Connection = setup_redis();
```

I was looking into that, too. However found two problems: Iron doesn't seem to give me any nice way to then pass that on to the specific request handler (at this current point), specifically when multiple requests are handled. I was thinking of digging deeper into iron at a later point to figure out how they do that for the Router so I could offer something similar, because otherwise the _one_ redis connection would become a bottleneck if many requests come in. Secondly I have no idea how this would behave in a multi threading scenario, as we need that in the background thread, too. So I opted for opening way to many parallel connections at the moment – redis for sure can handle it...

---

``` diff
diff --git a/src/handlers.rs b/src/handlers.rs
index 5425144..606c34b 100644
--- a/src/handlers.rs
+++ b/src/handlers.rs
@@ -93,11 +94,13 @@ pub fn github_finder(req: &mut Request) -> IronResult<Response> {
 pub fn github_handler(req: &mut Request) -> IronResult<Response> {
 ....

     let sha = router.find("sha").unwrap();
+    // this allocation is really unnecessary, you can just use an array of length 2 and fill it with the iterator. Or, just match on the full string.
     let filename: Vec<&str> = router.find("method")
                                     .unwrap_or("badge.svg")
                                     .rsplitn(2, '.')

```

I am not sure I understand what you mean here. Could you give me some pseudo code what you propose to do instead?

---

``` diff
--- a/src/helpers.rs
+++ b/src/helpers.rs
@@ -63,6 +63,7 @@ pub fn download_and_unzip(source_url: &str, tmp_dir: &TempDir) -> Result<Vec<Str
                                     let mut buffer: Vec<u8> = vec![];
                                     zip_file.read_to_end(&mut buffer).unwrap();
                                     writer.write(&buffer).unwrap();
+                                    // why not just return a vec of paths?
                                     paths.push(String::from(full_path.to_string_lossy()
                                                                      .into_owned()));
                                 }
```

Because then rustc yells at me...:

``` shell
   Compiling clippy_service v0.9.0 (file:///vagrant)
src/helpers.rs:43:1: 137:2 error: the trait `core::marker::Sized` is not implemented for the type `[u8]` [E0277]
src/helpers.rs: 43 pub fn download_and_unzip(source_url: &str, tmp_dir: &TempDir) -> Result<Vec<Path>, String> {
src/helpers.rs: 44
src/helpers.rs: 45     // Start by creating a hyper client, which tries to connect and requests
src/helpers.rs: 46     // the content of that url. Specifically for the github services, make sure
src/helpers.rs: 47     // to have defined the `UserAgent`- and `Accept` HTTP-Header.
src/helpers.rs: 48     //
                   ...
src/helpers.rs:43:1: 137:2 help: run `rustc --explain E0277` to see a detailed explanation
src/helpers.rs:43:1: 137:2 note: `[u8]` does not have a constant size known at compile-time
src/helpers.rs:43:1: 137:2 note: required because it appears within the type `std::sys::os_str::Slice`
src/helpers.rs:43:1: 137:2 note: required because it appears within the type `std::ffi::os_str::OsStr`
src/helpers.rs:43:1: 137:2 note: required because it appears within the type `std::path::Path`
src/helpers.rs:43:1: 137:2 note: required by `collections::vec::Vec`
error: aborting due to previous error
Could not compile `clippy_service`.

To learn more, run the command again with --verbose.
```

**Comment by Manishearth** [comment]
>  I think you might refer to the fact that branches (and tags) might reference a different SHA at another point in time

yeah, I meant that the SHA corresponding to a branch might change. 5 minutes sounds good.

>  Iron doesn't seem to give me any nice way to then pass that on to the specific request handler

Use a closure.

>  So I opted for opening way to many parallel connections at the moment – redis for sure can handle it

That works. I don't know how cheap Redis connections are :smile: 

>  Could you give me some pseudo code what you propose to do instead?

Take the split string, assign to `split_string`, and just assign `name` to `split_string[0]` and `ext` to `split_string[1]`. Or something.

> Because then rustc yells at me...:

Use a Vec of PathBufs, sorry. Path is like [T] and str, it's a slice type.

**Comment by Manishearth** [comment]
Oh, also, CCing the other clippy maintainers (@llogiq @mcarton @birkenfeld) for a sneak peek at this. It's hosted on http://clippy.bashy.io/, and creates a badge that can be placed in the readme sowing the number of clippy warnings.

Shields.io seems down at the moment though.

**Comment by Manishearth** [comment]
I wonder if we should also provide an API where you upload the clippy result for your crate instead of relying on a build server. However, authentication can be painful.

We then give people code to copy-paste into a travis or appveyor file. It's less push-button than this solution, but it lets us support a wider variety of setups and avoids load on the server.

**Comment by birkenfeld** [comment]
Very nice. Just tested with a few crates of mine; I saw that if the build fails the verdict is "success"...

**Comment by Manishearth** [comment]
That doesn't sound right.

**Comment by mcarton** [comment]
Also tested it, it reports warning in a file guarded by

``` rust
#![cfg_attr(feature="clippy", allow(float_cmp))]
```

Clippy is often used with a `clippy`, `dev`, `nightly`, `testing` or whatever feature in the wild, does the service have a way to compile with a given feature?

**Comment by Manishearth** [comment]
It doesn't need to, it threads the clippy dependency in through `-Zextra-plugins`. But yeah, another reason why it might be nice for users to be able to upload their own clippy logs via travis.

**Comment by mcarton** [comment]
I know it uses Clippy that way, but because it does that, it ignores the conditional allows I’ve put because I expect Clippy to be used with the `clippy` feature. [Other projects do similar things](https://github.com/kbknapp/clap-rs/blob/ab41be700b7c73b91953ecb6fd236bb2ec095a33/src/lib.rs#L383-L398).

**Comment by gnunicorn** [comment]
@birkenfeld : could you give me a link where a failing one gave you "success" (maybe as a new ticket)? I'd like to investigate that.

@Manishearth IF clippy created a standardized log-file (like coverage.py does) we could accept uploads of those – parse the results, provide the badge and give the option that a PR might be blocked if more warnings/errors are introduced. All of that goes beyond the scope of the v1.0 I am currently trying to push out, but I am happy to discuss those!

@Manishearth , @mcarton could you elaborate why the conf_attr things doesn't work in the rustc-approach I am currently taking? And maybe what we can do about that? Is this because the we don't pass that config? I was thinking of allowing some customisation of the rustc command via a `.clippy.toml` in the same folder. There the owner could configure they want "feature" xyz, would that solve the issue?

**Comment by gnunicorn** [comment]
@Manishearth 

> > Iron doesn't seem to give me any nice way to then pass that on to the specific request handler
> 
> Use a closure.

And how would I pass that to the handler? Or do you mean wrapping the clojure around the handler like this:

```

    mount.mount("/github/", router!(
        get "/sha/:user/:repo/:sha/:method" => |resp| handlers::github_handler(resp, redis_connection),
```

That's very ugly imho. In Python I'd usually use decorators for something like this. Does rust provide some concept like that?

---

The split string improvement you are suggesting doesn't always work. First because I am splitting from the end to get the extension, the order is reversed (`"svg", "badge"`), secondly I have items without extensions (`"log"`, `"state"`). So, the order of the method and the extension do depend on the len of the vector split and I am not always getting the same count – what would happen if I had a list of len==1 and I do this : `item = list[1];`? That'd happen otherwise.

**Comment by Manishearth** [comment]
>  IF clippy created a standardized log-file (like coverage.py does) we could accept uploads of those – parse the results, provide the badge and give the option that a PR might be blocked if more warnings/errors are introduced.

-Zextra-plugins -Lclippy --error-format=json _is_ a standardized log file :smile: 

(if not, clippy has its own stub structured logging framework that could be used.

> All of that goes beyond the scope of the v1.0

Right, we can talk about it later :smile: 

> could you elaborate why the conf_attr things doesn't work in the rustc-approach I am currently taking?

It's because different crates have a different Cargo feature for clippy. I've seen "nightly", "clippy", "dev", "plugins" used (the name often depends on if you have _other_ nightly-only deps).

> Does rust provide some concept like that?

https://github.com/manishearth/rust-adorn exists, but it's a proof of concept and probably doesn't compile now (I can make that happen if you need it). Rust prefers closures though, they're not that bad.

> The split string improvement you are suggesting doesn't always work. 

Just use an `if` on the len, then. `rsplit` returns a `&[&str]`, just store that in a variable instead of using a vec.

**Comment by gnunicorn** [comment]
Closing this for now. Moved custom feature discussion to #17 . Thanks again everyone and cheers to the launch: http://www.bashy.io/news/2016/03/05/clippy-linting-as-a-service/ \o/
